# Site settings
title: Mose bla
email: mose@mose.com
description: Random rant from mose.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://bla.mose.com/" # the base hostname & protocol for your site
twitter_username: mo5e
github_username:  mose

destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data

exclude:
- vendor
- README.md
- Dockerfile
- .ruby-version
- .bundle

encoding:     "utf-8"

markdown_ext: "md"

# Build settings
markdown: kramdown
